name: CI

env:
  YANDEX_AD_BLOCK_ID: ${{secrets.YANDEX_AD_BLOCK_ID}}

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install frontend deps
        run: yarn install --frozen-lockfile
        working-directory: frontend

      - name: Lint check
        run: yarn lint
        working-directory: frontend

      - name: Build frontend
        run: yarn build
        working-directory: frontend
