name: CI

env:
  YANDEX_AD_BLOCK_ID: ${{secrets.YANDEX_AD_BLOCK_ID}}

on:
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install frontend deps
        run: yarn install --frozen-lockfile
        working-directory: frontend

      - name: Build frontend
        run: yarn build
        working-directory: frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend deps
        run: npm ci
        working-directory: backend

      - name: Build backend
        run: npm run build
        working-directory: backend
