
   
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: 'yarn'
      - uses: actions/cache@v2.1.7
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn

      - name: Lint check
        run: yarn lint

      - name: Build
        run: yarn build